// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCunUDKuP6aYFCJyvFtQlVxAgjv_3zbaBg',
    appId: '1:839123146805:web:484f92430b04eb8f2d797c',
    messagingSenderId: '839123146805',
    projectId: 'peff-558c3',
    authDomain: 'peff-558c3.firebaseapp.com',
    storageBucket: 'peff-558c3.appspot.com',
    measurementId: 'G-VJ3Y90Y4JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHsFppSpNwr05WCcmgW7jt_8q65UN5v4Y',
    appId: '1:839123146805:android:0edfe4b7b9f62b0b2d797c',
    messagingSenderId: '839123146805',
    projectId: 'peff-558c3',
    storageBucket: 'peff-558c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRVW0VDIOT_5qDgpW0o2uGBFS6YK6zlxA',
    appId: '1:839123146805:ios:25c380e0434e00562d797c',
    messagingSenderId: '839123146805',
    projectId: 'peff-558c3',
    storageBucket: 'peff-558c3.appspot.com',
    iosBundleId: 'com.example.pettPeaces',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRVW0VDIOT_5qDgpW0o2uGBFS6YK6zlxA',
    appId: '1:839123146805:ios:25c380e0434e00562d797c',
    messagingSenderId: '839123146805',
    projectId: 'peff-558c3',
    storageBucket: 'peff-558c3.appspot.com',
    iosBundleId: 'com.example.pettPeaces',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCunUDKuP6aYFCJyvFtQlVxAgjv_3zbaBg',
    appId: '1:839123146805:web:2725c5682239f32d2d797c',
    messagingSenderId: '839123146805',
    projectId: 'peff-558c3',
    authDomain: 'peff-558c3.firebaseapp.com',
    storageBucket: 'peff-558c3.appspot.com',
    measurementId: 'G-X79N06F4PX',
  );
}
